In [1]:
import numpy as np

Numerical Python

numpy is faster than list and it is very easy

In [2]:
a = np.array([[1,2,3],[3,4,5]])

In [3]:
print(a)

[[1 2 3]
 [3 4 5]]


In [4]:
print(a.shape)

(2, 3)


In [5]:
print(a[0,2])

3


In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

2

In [8]:
a.itemsize

8

In [9]:
a.shape

(2, 3)

In [10]:
a.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [11]:
a


array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
a[:,2]

array([3, 5])

In [13]:
a = np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [14]:
a.min()

1.0

In [15]:
a.max()

3.0

In [16]:
a.sum()

20.0

In [17]:
a = np.array([[1,2,3],[3,4,5]])

In [18]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [19]:
a.sum(axis=0)

array([4, 6, 8])

In [20]:
a.sum(axis=1)

array([ 6, 12])

### stacking